# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'centroidsFlagTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CentroidFlagsDockWidget(object):
    def setupUi(self, CentroidFlagsDockWidget):
        CentroidFlagsDockWidget.setObjectName("CentroidFlagsDockWidget")
        CentroidFlagsDockWidget.resize(317, 456)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(
            5, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.flagsMapLayerComboBox = QgsMapLayerComboBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.flagsMapLayerComboBox.sizePolicy().hasHeightForWidth()
        )
        self.flagsMapLayerComboBox.setSizePolicy(sizePolicy)
        self.flagsMapLayerComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.flagsMapLayerComboBox.setObjectName("flagsMapLayerComboBox")
        self.flagsMapLayerComboBox.setFilters(core.QgsMapLayerProxyModel.PolygonLayer)
        self.horizontalLayout.addWidget(self.flagsMapLayerComboBox)
        self.refreshFlagsPushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.refreshFlagsPushButton.setEnabled(True)
        self.refreshFlagsPushButton.setStyleSheet("")
        self.refreshFlagsPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/plugins/DsgTools/icons/reload.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.refreshFlagsPushButton.setIcon(icon)
        self.refreshFlagsPushButton.setIconSize(QtCore.QSize(16, 16))
        self.refreshFlagsPushButton.setAutoExclusive(False)
        self.refreshFlagsPushButton.setObjectName("refreshFlagsPushButton")
        self.horizontalLayout.addWidget(self.refreshFlagsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            5, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pointsMapLayerComboBox = QgsMapLayerComboBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pointsMapLayerComboBox.sizePolicy().hasHeightForWidth()
        )
        self.pointsMapLayerComboBox.setSizePolicy(sizePolicy)
        self.pointsMapLayerComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.pointsMapLayerComboBox.setObjectName("pointsMapLayerComboBox")
        self.pointsMapLayerComboBox.setFilters(core.QgsMapLayerProxyModel.PointLayer)
        self.horizontalLayout_2.addWidget(self.pointsMapLayerComboBox)
        self.refreshPointsPushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.refreshPointsPushButton.setEnabled(True)
        self.refreshPointsPushButton.setStyleSheet("")
        self.refreshPointsPushButton.setText("")
        self.refreshPointsPushButton.setIcon(icon)
        self.refreshPointsPushButton.setIconSize(QtCore.QSize(16, 16))
        self.refreshPointsPushButton.setAutoExclusive(False)
        self.refreshPointsPushButton.setObjectName("refreshPointsPushButton")
        self.horizontalLayout_2.addWidget(self.refreshPointsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.attributeTable = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.attributeTable.setAlternatingRowColors(True)
        self.attributeTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.attributeTable.setObjectName("attributeTable")
        self.attributeTable.setColumnCount(0)
        self.attributeTable.setRowCount(0)
        self.gridLayout.addWidget(self.attributeTable, 1, 0, 1, 1)
        CentroidFlagsDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(CentroidFlagsDockWidget)
        QtCore.QMetaObject.connectSlotsByName(CentroidFlagsDockWidget)

    def retranslateUi(self, CentroidFlagsDockWidget):
        _translate = QtCore.QCoreApplication.translate
        CentroidFlagsDockWidget.setWindowTitle(
            _translate("CentroidFlagsDockWidget", "Inspect Centroid Flags Toolbox")
        )
        self.label.setText(_translate("CentroidFlagsDockWidget", "Camada de Flags"))
        self.label_2.setText(_translate("CentroidFlagsDockWidget", "Camada de Pontos"))


from qgis.gui import (
    QgsMapLayerComboBox,
)
from qgis import core
import resources_rc
