# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiLayersCentroidsFlagTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultiLayersCentroidsFlagDockWidget(object):
    def setupUi(self, MultiLayersCentroidsFlagDockWidget):
        MultiLayersCentroidsFlagDockWidget.setObjectName("MultiLayersCentroidsFlagDockWidget")
        MultiLayersCentroidsFlagDockWidget.resize(399, 300)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.flagsMapLayerComboBox = QgsMapLayerComboBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flagsMapLayerComboBox.sizePolicy().hasHeightForWidth())
        self.flagsMapLayerComboBox.setSizePolicy(sizePolicy)
        self.flagsMapLayerComboBox.setMinimumSize(QtCore.QSize(160, 0))
        self.flagsMapLayerComboBox.setMaximumSize(QtCore.QSize(181, 16777215))
        self.flagsMapLayerComboBox.setObjectName("flagsMapLayerComboBox")
        self.flagsMapLayerComboBox.setFilters(
            core.QgsMapLayerProxyModel.PolygonLayer
        )
        self.horizontalLayout.addWidget(self.flagsMapLayerComboBox)
        self.refreshFlagsPushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.refreshFlagsPushButton.setMinimumSize(QtCore.QSize(28, 24))
        self.refreshFlagsPushButton.setMaximumSize(QtCore.QSize(28, 24))
        self.refreshFlagsPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/DsgTools/icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshFlagsPushButton.setIcon(icon)
        self.refreshFlagsPushButton.setObjectName("refreshFlagsPushButton")
        self.horizontalLayout.addWidget(self.refreshFlagsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.multiLayersCentroidsPushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiLayersCentroidsPushButton.sizePolicy().hasHeightForWidth())
        self.multiLayersCentroidsPushButton.setSizePolicy(sizePolicy)
        self.multiLayersCentroidsPushButton.setMinimumSize(QtCore.QSize(100, 22))
        self.multiLayersCentroidsPushButton.setMaximumSize(QtCore.QSize(103, 22))
        self.multiLayersCentroidsPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/DsgTools/icons/multiple_layers_centroids_flags.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiLayersCentroidsPushButton.setIcon(icon1)
        self.multiLayersCentroidsPushButton.setIconSize(QtCore.QSize(111, 23))
        self.multiLayersCentroidsPushButton.setObjectName("multiLayersCentroidsPushButton")
        self.horizontalLayout_2.addWidget(self.multiLayersCentroidsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.attributeTable = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.attributeTable.setObjectName("attributeTable")
        self.attributeTable.setColumnCount(0)
        self.attributeTable.setRowCount(0)
        self.gridLayout.addWidget(self.attributeTable, 1, 0, 1, 1)
        MultiLayersCentroidsFlagDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(MultiLayersCentroidsFlagDockWidget)
        QtCore.QMetaObject.connectSlotsByName(MultiLayersCentroidsFlagDockWidget)

    def retranslateUi(self, MultiLayersCentroidsFlagDockWidget):
        _translate = QtCore.QCoreApplication.translate
        MultiLayersCentroidsFlagDockWidget.setWindowTitle(_translate("MultiLayersCentroidsFlagDockWidget", "Inspect Multi Layers Centroids Flags Toolbox"))
        self.label.setText(_translate("MultiLayersCentroidsFlagDockWidget", "Camada de Flags"))
        self.label_2.setText(_translate("MultiLayersCentroidsFlagDockWidget", "Camadas de Pontos"))
from qgsmaplayercombobox import QgsMapLayerComboBox
from qgis import core
import resources_rc
