# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mosaicTools.ui'
#
# Created: Thu Feb 26 15:56:23 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(557, 371)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.checkBox)
        self.label = QtGui.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.listView = QtGui.QListView(self.tab)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.horizontalLayout_2.addWidget(self.listView)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addButton = QtGui.QPushButton(self.tab)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.verticalLayout.addWidget(self.addButton)
        self.removeButton = QtGui.QPushButton(self.tab)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.verticalLayout.addWidget(self.removeButton)
        self.addFolderButton = QtGui.QPushButton(self.tab)
        self.addFolderButton.setObjectName(_fromUtf8("addFolderButton"))
        self.verticalLayout.addWidget(self.addFolderButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.procuraSRButton = QtGui.QPushButton(self.tab)
        self.procuraSRButton.setObjectName(_fromUtf8("procuraSRButton"))
        self.horizontalLayout.addWidget(self.procuraSRButton)
        self.formLayout.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_5)
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.metadataTemplateButton = QtGui.QPushButton(self.tab_2)
        self.metadataTemplateButton.setObjectName(_fromUtf8("metadataTemplateButton"))
        self.horizontalLayout_3.addWidget(self.metadataTemplateButton)
        self.formLayout_2.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.checkBox_2 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.SpanningRole, self.checkBox_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.outputFolderButton = QtGui.QPushButton(Dialog)
        self.outputFolderButton.setObjectName(_fromUtf8("outputFolderButton"))
        self.horizontalLayout_4.addWidget(self.outputFolderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Preparação de imagens para mosaicos", None))
        self.checkBox.setText(_translate("Dialog", "Processar as imagens", None))
        self.label.setText(_translate("Dialog", "Imagens de entrada:", None))
        self.addButton.setText(_translate("Dialog", "Adicionar", None))
        self.removeButton.setText(_translate("Dialog", "Remover", None))
        self.addFolderButton.setText(_translate("Dialog", "Adicionar pasta", None))
        self.label_4.setText(_translate("Dialog", "Sistema de referẽncia de saída", None))
        self.procuraSRButton.setText(_translate("Dialog", "Procurar SR", None))
        self.label_5.setText(_translate("Dialog", "Tipo de número nas imagens de saída:", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Byte with color palette", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Byte", None))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Unsigned Int 16", None))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Int 16", None))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Unsigned Int 32", None))
        self.comboBox_2.setItemText(5, _translate("Dialog", "Int 32", None))
        self.comboBox_2.setItemText(6, _translate("Dialog", "Float 32", None))
        self.comboBox_2.setItemText(7, _translate("Dialog", "Float 64", None))
        self.label_3.setText(_translate("Dialog", "Aplicar realce de contraste:", None))
        self.comboBox.setItemText(0, _translate("Dialog", "Nenhum", None))
        self.comboBox.setItemText(1, _translate("Dialog", "Linear 2%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Imagem", None))
        self.label_2.setText(_translate("Dialog", "Modelo XML do metadado de saída:", None))
        self.metadataTemplateButton.setText(_translate("Dialog", "Procurar", None))
        self.checkBox_2.setText(_translate("Dialog", "Processar os metadados", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Metadado", None))
        self.label_6.setText(_translate("Dialog", "Pasta dos arquivos de saída:", None))
        self.outputFolderButton.setText(_translate("Dialog", "Procurar", None))

