# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sec-SDT\.qgis2\python\plugins\DsgTools\LayerTools\load_by_category_dialog.ui'
#
# Created: Fri Mar 13 23:44:07 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LoadByCategory(object):
    def setupUi(self, LoadByCategory):
        LoadByCategory.setObjectName(_fromUtf8("LoadByCategory"))
        LoadByCategory.resize(551, 436)
        self.gridLayout_8 = QtGui.QGridLayout(LoadByCategory)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabWidget = QtGui.QTabWidget(LoadByCategory)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSpatialite = QtGui.QWidget()
        self.tabSpatialite.setObjectName(_fromUtf8("tabSpatialite"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabSpatialite)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tabSpatialite)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spatialiteFileEdit = QtGui.QLineEdit(self.tabSpatialite)
        self.spatialiteFileEdit.setObjectName(_fromUtf8("spatialiteFileEdit"))
        self.horizontalLayout.addWidget(self.spatialiteFileEdit)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonOpenFile = QtGui.QPushButton(self.tabSpatialite)
        self.pushButtonOpenFile.setObjectName(_fromUtf8("pushButtonOpenFile"))
        self.horizontalLayout.addWidget(self.pushButtonOpenFile)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tabSpatialite)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spatialiteCrsEdit = QtGui.QLineEdit(self.tabSpatialite)
        self.spatialiteCrsEdit.setObjectName(_fromUtf8("spatialiteCrsEdit"))
        self.horizontalLayout_2.addWidget(self.spatialiteCrsEdit)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpatialite, _fromUtf8(""))
        self.tabPostGIS = QtGui.QWidget()
        self.tabPostGIS.setObjectName(_fromUtf8("tabPostGIS"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabPostGIS)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabPostGIS)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBoxPostgis = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxPostgis.setObjectName(_fromUtf8("comboBoxPostgis"))
        self.verticalLayout.addWidget(self.comboBoxPostgis)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_12.addWidget(self.label_7)
        self.postGISCrsEdit = QtGui.QLineEdit(self.groupBox_3)
        self.postGISCrsEdit.setObjectName(_fromUtf8("postGISCrsEdit"))
        self.horizontalLayout_12.addWidget(self.postGISCrsEdit)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPostGIS, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox = QtGui.QGroupBox(LoadByCategory)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listWidgetCategoryFrom = QtGui.QListWidget(self.groupBox)
        self.listWidgetCategoryFrom.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidgetCategoryFrom.setObjectName(_fromUtf8("listWidgetCategoryFrom"))
        self.horizontalLayout_3.addWidget(self.listWidgetCategoryFrom)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButtonSelectAll = QtGui.QPushButton(self.groupBox)
        self.pushButtonSelectAll.setObjectName(_fromUtf8("pushButtonSelectAll"))
        self.verticalLayout_2.addWidget(self.pushButtonSelectAll)
        self.pushButtonSelectOne = QtGui.QPushButton(self.groupBox)
        self.pushButtonSelectOne.setObjectName(_fromUtf8("pushButtonSelectOne"))
        self.verticalLayout_2.addWidget(self.pushButtonSelectOne)
        self.pushButtonDeselectOne = QtGui.QPushButton(self.groupBox)
        self.pushButtonDeselectOne.setObjectName(_fromUtf8("pushButtonDeselectOne"))
        self.verticalLayout_2.addWidget(self.pushButtonDeselectOne)
        self.pushButtonDeselectAll = QtGui.QPushButton(self.groupBox)
        self.pushButtonDeselectAll.setObjectName(_fromUtf8("pushButtonDeselectAll"))
        self.verticalLayout_2.addWidget(self.pushButtonDeselectAll)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.listWidgetCategoryTo = QtGui.QListWidget(self.groupBox)
        self.listWidgetCategoryTo.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidgetCategoryTo.setObjectName(_fromUtf8("listWidgetCategoryTo"))
        self.horizontalLayout_3.addWidget(self.listWidgetCategoryTo)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(LoadByCategory)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBoxPoint = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxPoint.setObjectName(_fromUtf8("checkBoxPoint"))
        self.verticalLayout_3.addWidget(self.checkBoxPoint)
        self.checkBoxLine = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxLine.setObjectName(_fromUtf8("checkBoxLine"))
        self.verticalLayout_3.addWidget(self.checkBoxLine)
        self.checkBoxPolygon = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxPolygon.setObjectName(_fromUtf8("checkBoxPolygon"))
        self.verticalLayout_3.addWidget(self.checkBoxPolygon)
        self.checkBoxAll = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxAll.setObjectName(_fromUtf8("checkBoxAll"))
        self.verticalLayout_3.addWidget(self.checkBoxAll)
        self.checkBoxOnlyWithElements = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxOnlyWithElements.setObjectName(_fromUtf8("checkBoxOnlyWithElements"))
        self.verticalLayout_3.addWidget(self.checkBoxOnlyWithElements)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pushButtonOk = QtGui.QPushButton(LoadByCategory)
        self.pushButtonOk.setObjectName(_fromUtf8("pushButtonOk"))
        self.horizontalLayout_4.addWidget(self.pushButtonOk)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButtonCancel = QtGui.QPushButton(LoadByCategory)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_4.addWidget(self.pushButtonCancel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)

        self.retranslateUi(LoadByCategory)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(LoadByCategory)

    def retranslateUi(self, LoadByCategory):
        LoadByCategory.setWindowTitle(QtGui.QApplication.translate("LoadByCategory", "Load Layers by Category", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LoadByCategory", "File                    ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOpenFile.setText(QtGui.QApplication.translate("LoadByCategory", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LoadByCategory", "Coordinate System", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpatialite), QtGui.QApplication.translate("LoadByCategory", "Spatialite", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("LoadByCategory", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("LoadByCategory", "Coordinate System", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPostGIS), QtGui.QApplication.translate("LoadByCategory", "PostGIS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("LoadByCategory", "Load by Category", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelectAll.setToolTip(QtGui.QApplication.translate("LoadByCategory", "Select all categories in the database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelectAll.setText(QtGui.QApplication.translate("LoadByCategory", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelectOne.setToolTip(QtGui.QApplication.translate("LoadByCategory", "Select only the selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSelectOne.setText(QtGui.QApplication.translate("LoadByCategory", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeselectOne.setToolTip(QtGui.QApplication.translate("LoadByCategory", "Remove from list only the selected categories", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeselectOne.setText(QtGui.QApplication.translate("LoadByCategory", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeselectAll.setToolTip(QtGui.QApplication.translate("LoadByCategory", "Remove all categories", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeselectAll.setText(QtGui.QApplication.translate("LoadByCategory", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("LoadByCategory", "Group by Geometry Type", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPoint.setText(QtGui.QApplication.translate("LoadByCategory", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLine.setText(QtGui.QApplication.translate("LoadByCategory", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPolygon.setText(QtGui.QApplication.translate("LoadByCategory", "Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAll.setText(QtGui.QApplication.translate("LoadByCategory", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOnlyWithElements.setText(QtGui.QApplication.translate("LoadByCategory", "Only layers with Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("LoadByCategory", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("LoadByCategory", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

