# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_by_class_base.ui'
#
# Created: Mon Dec 15 21:35:12 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LoadByClass(object):
    def setupUi(self, LoadByClass):
        LoadByClass.setObjectName(_fromUtf8("LoadByClass"))
        LoadByClass.resize(450, 650)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoadByClass.sizePolicy().hasHeightForWidth())
        LoadByClass.setSizePolicy(sizePolicy)
        LoadByClass.setMinimumSize(QtCore.QSize(450, 650))
        LoadByClass.setMaximumSize(QtCore.QSize(450, 650))
        self.tabWidgetLoadByClass = QtGui.QTabWidget(LoadByClass)
        self.tabWidgetLoadByClass.setGeometry(QtCore.QRect(10, 10, 411, 181))
        self.tabWidgetLoadByClass.setObjectName(_fromUtf8("tabWidgetLoadByClass"))
        self.tabSpatialite = QtGui.QWidget()
        self.tabSpatialite.setObjectName(_fromUtf8("tabSpatialite"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tabSpatialite)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 90, 361, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.crsLineEditLoadByClassSpatialite = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.crsLineEditLoadByClassSpatialite.setObjectName(_fromUtf8("crsLineEditLoadByClassSpatialite"))
        self.horizontalLayout_2.addWidget(self.crsLineEditLoadByClassSpatialite)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabSpatialite)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 361, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.fileLineEditLoadByClass = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.fileLineEditLoadByClass.setObjectName(_fromUtf8("fileLineEditLoadByClass"))
        self.horizontalLayout.addWidget(self.fileLineEditLoadByClass)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonOpenFile = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonOpenFile.setObjectName(_fromUtf8("pushButtonOpenFile"))
        self.horizontalLayout.addWidget(self.pushButtonOpenFile)
        self.tabWidgetLoadByClass.addTab(self.tabSpatialite, _fromUtf8(""))
        self.tabPostGIS = QtGui.QWidget()
        self.tabPostGIS.setObjectName(_fromUtf8("tabPostGIS"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabPostGIS)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 391, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayoutWidget_9 = QtGui.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(20, 90, 361, 41))
        self.horizontalLayoutWidget_9.setObjectName(_fromUtf8("horizontalLayoutWidget_9"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_12.addWidget(self.label_7)
        self.coordSysLineEditCarregaClassePostgis = QtGui.QLineEdit(self.horizontalLayoutWidget_9)
        self.coordSysLineEditCarregaClassePostgis.setObjectName(_fromUtf8("coordSysLineEditCarregaClassePostgis"))
        self.horizontalLayout_12.addWidget(self.coordSysLineEditCarregaClassePostgis)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.layoutWidget = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 21, 361, 64))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBoxPostgis = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxPostgis.setObjectName(_fromUtf8("comboBoxPostgis"))
        self.verticalLayout.addWidget(self.comboBoxPostgis)
        self.tabWidgetLoadByClass.addTab(self.tabPostGIS, _fromUtf8(""))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(LoadByClass)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 600, 350, 44))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.pushButtonOkLoadByClass = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonOkLoadByClass.setObjectName(_fromUtf8("pushButtonOkLoadByClass"))
        self.horizontalLayout_9.addWidget(self.pushButtonOkLoadByClass)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.pushButtonCancelLoadByClass = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonCancelLoadByClass.setObjectName(_fromUtf8("pushButtonCancelLoadByClass"))
        self.horizontalLayout_9.addWidget(self.pushButtonCancelLoadByClass)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.groupBox = QtGui.QGroupBox(LoadByClass)
        self.groupBox.setGeometry(QtCore.QRect(30, 210, 380, 331))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 360, 311))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listWidgetClassesLoadByClass = QtGui.QListWidget(self.horizontalLayoutWidget_3)
        self.listWidgetClassesLoadByClass.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidgetClassesLoadByClass.setObjectName(_fromUtf8("listWidgetClassesLoadByClass"))
        self.horizontalLayout_3.addWidget(self.listWidgetClassesLoadByClass)
        self.verticalLayoutWidget_2 = QtGui.QWidget(LoadByClass)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 550, 185, 42))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBoxSelectAllLoadByClass = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxSelectAllLoadByClass.setObjectName(_fromUtf8("checkBoxSelectAllLoadByClass"))
        self.verticalLayout_2.addWidget(self.checkBoxSelectAllLoadByClass)

        self.retranslateUi(LoadByClass)
        self.tabWidgetLoadByClass.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(LoadByClass)

    def retranslateUi(self, LoadByClass):
        LoadByClass.setWindowTitle(_translate("LoadByClass", "Load by Class", None))
        self.label_2.setText(_translate("LoadByClass", "Coordinate System", None))
        self.label.setText(_translate("LoadByClass", "File                    ", None))
        self.pushButtonOpenFile.setText(_translate("LoadByClass", "Search", None))
        self.tabWidgetLoadByClass.setTabText(self.tabWidgetLoadByClass.indexOf(self.tabSpatialite), _translate("LoadByClass", "Spatialite", None))
        self.groupBox_3.setTitle(_translate("LoadByClass", "Connections", None))
        self.label_7.setText(_translate("LoadByClass", "Coordinate System", None))
        self.tabWidgetLoadByClass.setTabText(self.tabWidgetLoadByClass.indexOf(self.tabPostGIS), _translate("LoadByClass", "PostGIS", None))
        self.pushButtonOkLoadByClass.setText(_translate("LoadByClass", "Ok", None))
        self.pushButtonCancelLoadByClass.setText(_translate("LoadByClass", "Cancel", None))
        self.groupBox.setTitle(_translate("LoadByClass", "Select the classes", None))
        self.checkBoxSelectAllLoadByClass.setText(_translate("LoadByClass", "Select All", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    LoadByClass = QtGui.QWidget()
    ui = Ui_LoadByClass()
    ui.setupUi(LoadByClass)
    LoadByClass.show()
    sys.exit(app.exec_())

