# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_create_inom_dialog_base.ui'
#
# Created: Fri Dec 19 11:25:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(306, 356)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSpatialite = QtGui.QWidget()
        self.tabSpatialite.setObjectName(_fromUtf8("tabSpatialite"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabSpatialite)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_16 = QtGui.QLabel(self.tabSpatialite)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.spatialiteFileEdit = QtGui.QLineEdit(self.tabSpatialite)
        self.spatialiteFileEdit.setObjectName(_fromUtf8("spatialiteFileEdit"))
        self.horizontalLayout_5.addWidget(self.spatialiteFileEdit)
        self.pushButtonOpenFile = QtGui.QPushButton(self.tabSpatialite)
        self.pushButtonOpenFile.setObjectName(_fromUtf8("pushButtonOpenFile"))
        self.horizontalLayout_5.addWidget(self.pushButtonOpenFile)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_17 = QtGui.QLabel(self.tabSpatialite)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_6.addWidget(self.label_17)
        self.spatialiteCrsEdit = QtGui.QLineEdit(self.tabSpatialite)
        self.spatialiteCrsEdit.setObjectName(_fromUtf8("spatialiteCrsEdit"))
        self.horizontalLayout_6.addWidget(self.spatialiteCrsEdit)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpatialite, _fromUtf8(""))
        self.tabPostGIS = QtGui.QWidget()
        self.tabPostGIS.setObjectName(_fromUtf8("tabPostGIS"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabPostGIS)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabPostGIS)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBoxPostgis = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxPostgis.setObjectName(_fromUtf8("comboBoxPostgis"))
        self.verticalLayout_2.addWidget(self.comboBoxPostgis)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.postGISCrsEdit = QtGui.QLineEdit(self.groupBox_3)
        self.postGISCrsEdit.setObjectName(_fromUtf8("postGISCrsEdit"))
        self.horizontalLayout_12.addWidget(self.postGISCrsEdit)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPostGIS, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.scaleCombo = QtGui.QComboBox(Dialog)
        self.scaleCombo.setObjectName(_fromUtf8("scaleCombo"))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.scaleCombo)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.Spatia = QtGui.QGroupBox(Dialog)
        self.Spatia.setObjectName(_fromUtf8("Spatia"))
        self.gridLayout = QtGui.QGridLayout(self.Spatia)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mirRadioButton = QtGui.QRadioButton(self.Spatia)
        self.mirRadioButton.setMinimumSize(QtCore.QSize(60, 0))
        self.mirRadioButton.setObjectName(_fromUtf8("mirRadioButton"))
        self.horizontalLayout.addWidget(self.mirRadioButton)
        self.mirLineEdit = QtGui.QLineEdit(self.Spatia)
        self.mirLineEdit.setObjectName(_fromUtf8("mirLineEdit"))
        self.horizontalLayout.addWidget(self.mirLineEdit)
        spacerItem2 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.miRadioButton = QtGui.QRadioButton(self.Spatia)
        self.miRadioButton.setMinimumSize(QtCore.QSize(60, 0))
        self.miRadioButton.setObjectName(_fromUtf8("miRadioButton"))
        self.horizontalLayout_2.addWidget(self.miRadioButton)
        self.miLineEdit = QtGui.QLineEdit(self.Spatia)
        self.miLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.miLineEdit.setObjectName(_fromUtf8("miLineEdit"))
        self.horizontalLayout_2.addWidget(self.miLineEdit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.inomRadioButton = QtGui.QRadioButton(self.Spatia)
        self.inomRadioButton.setMinimumSize(QtCore.QSize(60, 0))
        self.inomRadioButton.setObjectName(_fromUtf8("inomRadioButton"))
        self.horizontalLayout_3.addWidget(self.inomRadioButton)
        self.inomLineEdit = QtGui.QLineEdit(self.Spatia)
        self.inomLineEdit.setObjectName(_fromUtf8("inomLineEdit"))
        self.horizontalLayout_3.addWidget(self.inomLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.wktRadioButton = QtGui.QRadioButton(self.Spatia)
        self.wktRadioButton.setMinimumSize(QtCore.QSize(60, 0))
        self.wktRadioButton.setObjectName(_fromUtf8("wktRadioButton"))
        self.horizontalLayout_4.addWidget(self.wktRadioButton)
        self.wktLineEdit = QtGui.QLineEdit(self.Spatia)
        self.wktLineEdit.setObjectName(_fromUtf8("wktLineEdit"))
        self.horizontalLayout_4.addWidget(self.wktLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.Spatia, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.okButton = QtGui.QPushButton(Dialog)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout_8.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_8.addWidget(self.cancelButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Create Frame", None))
        self.label_16.setText(_translate("Dialog", "File                    ", None))
        self.pushButtonOpenFile.setText(_translate("Dialog", "Search", None))
        self.label_17.setText(_translate("Dialog", "Coordinate System", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpatialite), _translate("Dialog", "Spatialite", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Connections", None))
        self.label_18.setText(_translate("Dialog", "Coordinate System", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPostGIS), _translate("Dialog", "PostGIS", None))
        self.label.setText(_translate("Dialog", "Scale:", None))
        self.scaleCombo.setItemText(0, _translate("Dialog", "1000k", None))
        self.scaleCombo.setItemText(1, _translate("Dialog", "500k", None))
        self.scaleCombo.setItemText(2, _translate("Dialog", "250k", None))
        self.scaleCombo.setItemText(3, _translate("Dialog", "100k", None))
        self.scaleCombo.setItemText(4, _translate("Dialog", "50k", None))
        self.scaleCombo.setItemText(5, _translate("Dialog", "25k", None))
        self.scaleCombo.setItemText(6, _translate("Dialog", "10k", None))
        self.scaleCombo.setItemText(7, _translate("Dialog", "5k", None))
        self.scaleCombo.setItemText(8, _translate("Dialog", "2k", None))
        self.scaleCombo.setItemText(9, _translate("Dialog", "1k", None))
        self.Spatia.setTitle(_translate("Dialog", "Index Frame Selection", None))
        self.mirRadioButton.setText(_translate("Dialog", "MIR:", None))
        self.miRadioButton.setText(_translate("Dialog", "MI:", None))
        self.inomRadioButton.setText(_translate("Dialog", "Index:", None))
        self.wktRadioButton.setText(_translate("Dialog", "WKT:", None))
        self.okButton.setText(_translate("Dialog", "Ok", None))
        self.cancelButton.setText(_translate("Dialog", "Cancel", None))

