# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_create_inom_dialog_base.ui'
#
# Created: Thu Dec 18 15:54:18 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(529, 393)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSpatialite = QtGui.QWidget()
        self.tabSpatialite.setObjectName(_fromUtf8("tabSpatialite"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabSpatialite)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_16 = QtGui.QLabel(self.tabSpatialite)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.spatialiteFileEdit = QtGui.QLineEdit(self.tabSpatialite)
        self.spatialiteFileEdit.setObjectName(_fromUtf8("spatialiteFileEdit"))
        self.horizontalLayout_5.addWidget(self.spatialiteFileEdit)
        self.pushButtonOpenFile = QtGui.QPushButton(self.tabSpatialite)
        self.pushButtonOpenFile.setObjectName(_fromUtf8("pushButtonOpenFile"))
        self.horizontalLayout_5.addWidget(self.pushButtonOpenFile)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_17 = QtGui.QLabel(self.tabSpatialite)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_6.addWidget(self.label_17)
        self.spatialiteCrsEdit = QtGui.QLineEdit(self.tabSpatialite)
        self.spatialiteCrsEdit.setObjectName(_fromUtf8("spatialiteCrsEdit"))
        self.horizontalLayout_6.addWidget(self.spatialiteCrsEdit)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpatialite, _fromUtf8(""))
        self.tabPostGIS = QtGui.QWidget()
        self.tabPostGIS.setObjectName(_fromUtf8("tabPostGIS"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabPostGIS)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabPostGIS)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBoxPostgis = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxPostgis.setObjectName(_fromUtf8("comboBoxPostgis"))
        self.verticalLayout_2.addWidget(self.comboBoxPostgis)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.postGISCrsEdit = QtGui.QLineEdit(self.groupBox_3)
        self.postGISCrsEdit.setObjectName(_fromUtf8("postGISCrsEdit"))
        self.horizontalLayout_12.addWidget(self.postGISCrsEdit)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPostGIS, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.inomLineEdit = QtGui.QLineEdit(Dialog)
        self.inomLineEdit.setEnabled(True)
        self.inomLineEdit.setObjectName(_fromUtf8("inomLineEdit"))
        self.horizontalLayout.addWidget(self.inomLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_3.addWidget(self.label_15)
        self.scaleComboBox = QtGui.QComboBox(Dialog)
        self.scaleComboBox.setObjectName(_fromUtf8("scaleComboBox"))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.scaleComboBox)
        spacerItem2 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.hemisphereComboBox = QtGui.QComboBox(Dialog)
        self.hemisphereComboBox.setObjectName(_fromUtf8("hemisphereComboBox"))
        self.hemisphereComboBox.addItem(_fromUtf8(""))
        self.hemisphereComboBox.addItem(_fromUtf8(""))
        self.hemisphereComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.hemisphereComboBox, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.latitudeComboBox = QtGui.QComboBox(Dialog)
        self.latitudeComboBox.setObjectName(_fromUtf8("latitudeComboBox"))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.latitudeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.latitudeComboBox, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.longitudeComboBox = QtGui.QComboBox(Dialog)
        self.longitudeComboBox.setObjectName(_fromUtf8("longitudeComboBox"))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.longitudeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.longitudeComboBox, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.comboBox500k = QtGui.QComboBox(Dialog)
        self.comboBox500k.setObjectName(_fromUtf8("comboBox500k"))
        self.comboBox500k.addItem(_fromUtf8(""))
        self.comboBox500k.addItem(_fromUtf8(""))
        self.comboBox500k.addItem(_fromUtf8(""))
        self.comboBox500k.addItem(_fromUtf8(""))
        self.comboBox500k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox500k, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.comboBox250k = QtGui.QComboBox(Dialog)
        self.comboBox250k.setObjectName(_fromUtf8("comboBox250k"))
        self.comboBox250k.addItem(_fromUtf8(""))
        self.comboBox250k.addItem(_fromUtf8(""))
        self.comboBox250k.addItem(_fromUtf8(""))
        self.comboBox250k.addItem(_fromUtf8(""))
        self.comboBox250k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox250k, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.comboBox100k = QtGui.QComboBox(Dialog)
        self.comboBox100k.setObjectName(_fromUtf8("comboBox100k"))
        self.comboBox100k.addItem(_fromUtf8(""))
        self.comboBox100k.addItem(_fromUtf8(""))
        self.comboBox100k.addItem(_fromUtf8(""))
        self.comboBox100k.addItem(_fromUtf8(""))
        self.comboBox100k.addItem(_fromUtf8(""))
        self.comboBox100k.addItem(_fromUtf8(""))
        self.comboBox100k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox100k, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.comboBox50k = QtGui.QComboBox(Dialog)
        self.comboBox50k.setObjectName(_fromUtf8("comboBox50k"))
        self.comboBox50k.addItem(_fromUtf8(""))
        self.comboBox50k.addItem(_fromUtf8(""))
        self.comboBox50k.addItem(_fromUtf8(""))
        self.comboBox50k.addItem(_fromUtf8(""))
        self.comboBox50k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox50k, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.comboBox25k = QtGui.QComboBox(Dialog)
        self.comboBox25k.setObjectName(_fromUtf8("comboBox25k"))
        self.comboBox25k.addItem(_fromUtf8(""))
        self.comboBox25k.addItem(_fromUtf8(""))
        self.comboBox25k.addItem(_fromUtf8(""))
        self.comboBox25k.addItem(_fromUtf8(""))
        self.comboBox25k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox25k, 3, 3, 1, 1)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.comboBox10k = QtGui.QComboBox(Dialog)
        self.comboBox10k.setObjectName(_fromUtf8("comboBox10k"))
        self.comboBox10k.addItem(_fromUtf8(""))
        self.comboBox10k.addItem(_fromUtf8(""))
        self.comboBox10k.addItem(_fromUtf8(""))
        self.comboBox10k.addItem(_fromUtf8(""))
        self.comboBox10k.addItem(_fromUtf8(""))
        self.comboBox10k.addItem(_fromUtf8(""))
        self.comboBox10k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox10k, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.comboBox5k = QtGui.QComboBox(Dialog)
        self.comboBox5k.setObjectName(_fromUtf8("comboBox5k"))
        self.comboBox5k.addItem(_fromUtf8(""))
        self.comboBox5k.addItem(_fromUtf8(""))
        self.comboBox5k.addItem(_fromUtf8(""))
        self.comboBox5k.addItem(_fromUtf8(""))
        self.comboBox5k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox5k, 4, 3, 1, 1)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.comboBox2k = QtGui.QComboBox(Dialog)
        self.comboBox2k.setObjectName(_fromUtf8("comboBox2k"))
        self.comboBox2k.addItem(_fromUtf8(""))
        self.comboBox2k.addItem(_fromUtf8(""))
        self.comboBox2k.addItem(_fromUtf8(""))
        self.comboBox2k.addItem(_fromUtf8(""))
        self.comboBox2k.addItem(_fromUtf8(""))
        self.comboBox2k.addItem(_fromUtf8(""))
        self.comboBox2k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox2k, 5, 1, 1, 1)
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 5, 2, 1, 1)
        self.comboBox1k = QtGui.QComboBox(Dialog)
        self.comboBox1k.setObjectName(_fromUtf8("comboBox1k"))
        self.comboBox1k.addItem(_fromUtf8(""))
        self.comboBox1k.addItem(_fromUtf8(""))
        self.comboBox1k.addItem(_fromUtf8(""))
        self.comboBox1k.addItem(_fromUtf8(""))
        self.comboBox1k.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox1k, 5, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.loadMILineEdit = QtGui.QLineEdit(Dialog)
        self.loadMILineEdit.setObjectName(_fromUtf8("loadMILineEdit"))
        self.horizontalLayout_2.addWidget(self.loadMILineEdit)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Create Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "File                    ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOpenFile.setText(QtGui.QApplication.translate("Dialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Coordinate System", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpatialite), QtGui.QApplication.translate("Dialog", "Spatialite", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Coordinate System", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPostGIS), QtGui.QApplication.translate("Dialog", "PostGIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "INOM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "1:1.000.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "1:500.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "1:250.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "1:100.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "1:50.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(6, QtGui.QApplication.translate("Dialog", "1:25.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(7, QtGui.QApplication.translate("Dialog", "1:10.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(8, QtGui.QApplication.translate("Dialog", "1:5.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(9, QtGui.QApplication.translate("Dialog", "1:2.000", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(10, QtGui.QApplication.translate("Dialog", "1:1.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Hemisphere:", None, QtGui.QApplication.UnicodeUTF8))
        self.hemisphereComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.hemisphereComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.hemisphereComboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(6, QtGui.QApplication.translate("Dialog", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(7, QtGui.QApplication.translate("Dialog", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(8, QtGui.QApplication.translate("Dialog", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(9, QtGui.QApplication.translate("Dialog", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(10, QtGui.QApplication.translate("Dialog", "J", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(11, QtGui.QApplication.translate("Dialog", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(12, QtGui.QApplication.translate("Dialog", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(13, QtGui.QApplication.translate("Dialog", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(14, QtGui.QApplication.translate("Dialog", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(15, QtGui.QApplication.translate("Dialog", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(16, QtGui.QApplication.translate("Dialog", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(17, QtGui.QApplication.translate("Dialog", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(18, QtGui.QApplication.translate("Dialog", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(19, QtGui.QApplication.translate("Dialog", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(20, QtGui.QApplication.translate("Dialog", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(21, QtGui.QApplication.translate("Dialog", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(22, QtGui.QApplication.translate("Dialog", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeComboBox.setItemText(23, QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(6, QtGui.QApplication.translate("Dialog", "06", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(7, QtGui.QApplication.translate("Dialog", "07", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(8, QtGui.QApplication.translate("Dialog", "08", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(9, QtGui.QApplication.translate("Dialog", "09", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(10, QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(11, QtGui.QApplication.translate("Dialog", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(12, QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(13, QtGui.QApplication.translate("Dialog", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(14, QtGui.QApplication.translate("Dialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(15, QtGui.QApplication.translate("Dialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(16, QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(17, QtGui.QApplication.translate("Dialog", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(18, QtGui.QApplication.translate("Dialog", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(19, QtGui.QApplication.translate("Dialog", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(20, QtGui.QApplication.translate("Dialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(21, QtGui.QApplication.translate("Dialog", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(22, QtGui.QApplication.translate("Dialog", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(23, QtGui.QApplication.translate("Dialog", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(24, QtGui.QApplication.translate("Dialog", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(25, QtGui.QApplication.translate("Dialog", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(26, QtGui.QApplication.translate("Dialog", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(27, QtGui.QApplication.translate("Dialog", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(28, QtGui.QApplication.translate("Dialog", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(29, QtGui.QApplication.translate("Dialog", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(30, QtGui.QApplication.translate("Dialog", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(31, QtGui.QApplication.translate("Dialog", "31", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(32, QtGui.QApplication.translate("Dialog", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(33, QtGui.QApplication.translate("Dialog", "33", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(34, QtGui.QApplication.translate("Dialog", "34", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(35, QtGui.QApplication.translate("Dialog", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(36, QtGui.QApplication.translate("Dialog", "36", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(37, QtGui.QApplication.translate("Dialog", "37", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(38, QtGui.QApplication.translate("Dialog", "38", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(39, QtGui.QApplication.translate("Dialog", "39", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(40, QtGui.QApplication.translate("Dialog", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(41, QtGui.QApplication.translate("Dialog", "41", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(42, QtGui.QApplication.translate("Dialog", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(43, QtGui.QApplication.translate("Dialog", "43", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(44, QtGui.QApplication.translate("Dialog", "44", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(45, QtGui.QApplication.translate("Dialog", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(46, QtGui.QApplication.translate("Dialog", "46", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(47, QtGui.QApplication.translate("Dialog", "47", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(48, QtGui.QApplication.translate("Dialog", "48", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(49, QtGui.QApplication.translate("Dialog", "49", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(50, QtGui.QApplication.translate("Dialog", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(51, QtGui.QApplication.translate("Dialog", "51", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(52, QtGui.QApplication.translate("Dialog", "52", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(53, QtGui.QApplication.translate("Dialog", "53", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(54, QtGui.QApplication.translate("Dialog", "54", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(55, QtGui.QApplication.translate("Dialog", "55", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(56, QtGui.QApplication.translate("Dialog", "56", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(57, QtGui.QApplication.translate("Dialog", "57", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(58, QtGui.QApplication.translate("Dialog", "58", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(59, QtGui.QApplication.translate("Dialog", "59", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeComboBox.setItemText(60, QtGui.QApplication.translate("Dialog", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "1:500.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox500k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox500k.setItemText(1, QtGui.QApplication.translate("Dialog", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox500k.setItemText(2, QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox500k.setItemText(3, QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox500k.setItemText(4, QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "1:250.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox250k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox250k.setItemText(1, QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox250k.setItemText(2, QtGui.QApplication.translate("Dialog", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox250k.setItemText(3, QtGui.QApplication.translate("Dialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox250k.setItemText(4, QtGui.QApplication.translate("Dialog", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "1:100.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox100k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox100k.setItemText(1, QtGui.QApplication.translate("Dialog", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox100k.setItemText(2, QtGui.QApplication.translate("Dialog", "II", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox100k.setItemText(3, QtGui.QApplication.translate("Dialog", "III", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox100k.setItemText(4, QtGui.QApplication.translate("Dialog", "IV", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox100k.setItemText(5, QtGui.QApplication.translate("Dialog", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox100k.setItemText(6, QtGui.QApplication.translate("Dialog", "VI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "1:50.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox50k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox50k.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox50k.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox50k.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox50k.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "1:25.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox25k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox25k.setItemText(1, QtGui.QApplication.translate("Dialog", "NO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox25k.setItemText(2, QtGui.QApplication.translate("Dialog", "NE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox25k.setItemText(3, QtGui.QApplication.translate("Dialog", "SO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox25k.setItemText(4, QtGui.QApplication.translate("Dialog", "SE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "1:10.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox10k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox10k.setItemText(1, QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox10k.setItemText(2, QtGui.QApplication.translate("Dialog", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox10k.setItemText(3, QtGui.QApplication.translate("Dialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox10k.setItemText(4, QtGui.QApplication.translate("Dialog", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox10k.setItemText(5, QtGui.QApplication.translate("Dialog", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox10k.setItemText(6, QtGui.QApplication.translate("Dialog", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "1:5.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox5k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox5k.setItemText(1, QtGui.QApplication.translate("Dialog", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox5k.setItemText(2, QtGui.QApplication.translate("Dialog", "II", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox5k.setItemText(3, QtGui.QApplication.translate("Dialog", "III", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox5k.setItemText(4, QtGui.QApplication.translate("Dialog", "IV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "1:2.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2k.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2k.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2k.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2k.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2k.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2k.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "1:1.000:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox1k.setItemText(0, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox1k.setItemText(1, QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox1k.setItemText(2, QtGui.QApplication.translate("Dialog", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox1k.setItemText(3, QtGui.QApplication.translate("Dialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox1k.setItemText(4, QtGui.QApplication.translate("Dialog", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Load MI:", None, QtGui.QApplication.UnicodeUTF8))

