ALTER TABLE cb.adm_area_pub_civil_a
  DROP CONSTRAINT adm_area_pub_civil_a_id_org_pub_civil_fk#
ALTER TABLE cb.adm_area_pub_militar_a
  DROP CONSTRAINT adm_area_pub_militar_a_id_org_pub_militar_fk#
ALTER TABLE cb.adm_edif_pub_civil_a
  DROP CONSTRAINT adm_edif_pub_civil_a_id_org_pub_civil_fk#
ALTER TABLE cb.adm_edif_pub_civil_p
  DROP CONSTRAINT adm_edif_pub_civil_p_id_org_pub_civil_fk#
ALTER TABLE cb.adm_edif_pub_militar_a
  DROP CONSTRAINT adm_edif_pub_militar_a_id_org_pub_militar_fk#
ALTER TABLE cb.adm_edif_pub_militar_p
  DROP CONSTRAINT adm_edif_pub_militar_p_id_org_pub_militar_fk#
ALTER TABLE complexos.adm_instituicao_publica
  DROP CONSTRAINT adm_instituicao_publica_id_instituicao_publica_fk#
ALTER TABLE complexos.adm_org_pub_civil
  DROP CONSTRAINT adm_org_pub_civil_id_org_pub_civil_fk#
ALTER TABLE complexos.adm_org_pub_civil
  DROP CONSTRAINT adm_org_pub_civil_id_instituicao_publica_fk#
ALTER TABLE complexos.adm_org_pub_militar
  DROP CONSTRAINT adm_org_pub_militar_id_org_pub_militar_fk#
ALTER TABLE complexos.adm_org_pub_militar
  DROP CONSTRAINT adm_org_pub_militar_id_instituicao_publica_fk#
ALTER TABLE cb.adm_posto_fiscal
  DROP CONSTRAINT adm_posto_fiscal_id_org_pub_civil_fk#
ALTER TABLE cb.adm_posto_fiscal_a
  DROP CONSTRAINT adm_posto_fiscal_a_id_org_pub_civil_fk#
ALTER TABLE cb.adm_posto_fiscal_p
  DROP CONSTRAINT adm_posto_fiscal_p_id_org_pub_civil_fk#
ALTER TABLE cb.adm_posto_pol_rod
  DROP CONSTRAINT adm_posto_pol_rod_id_org_pub_militar_fk#
ALTER TABLE cb.adm_posto_pol_rod
  DROP CONSTRAINT adm_posto_pol_rod_id_org_pub_civil_fk#
ALTER TABLE cb.adm_posto_pol_rod_a
  DROP CONSTRAINT adm_posto_pol_rod_a_id_org_pub_civil_fk#
ALTER TABLE cb.adm_posto_pol_rod_a
  DROP CONSTRAINT adm_posto_pol_rod_a_id_org_pub_militar_fk#
ALTER TABLE cb.adm_posto_pol_rod_p
  DROP CONSTRAINT adm_posto_pol_rod_p_id_org_pub_civil_fk#
ALTER TABLE cb.adm_posto_pol_rod_p
  DROP CONSTRAINT adm_posto_pol_rod_p_id_org_pub_militar_fk#
ALTER TABLE cb.asb_area_abast_agua_a
  DROP CONSTRAINT asb_area_abast_agua_a_id_complexo_abast_agua_fk#
ALTER TABLE cb.asb_area_saneamento_a
  DROP CONSTRAINT asb_area_saneamento_a_id_complexo_saneamento_fk#
ALTER TABLE complexos.asb_complexo_abast_agua
  DROP CONSTRAINT asb_complexo_abast_agua_id_org_comerc_serv_fk#
ALTER TABLE complexos.asb_complexo_saneamento
  DROP CONSTRAINT asb_complexo_saneamento_id_org_comerc_serv_fk#
ALTER TABLE cb.asb_dep_abast_agua
  DROP CONSTRAINT asb_dep_abast_agua_id_complexo_abast_agua_fk#
ALTER TABLE cb.asb_dep_abast_agua_a
  DROP CONSTRAINT asb_dep_abast_agua_a_id_complexo_abast_agua_fk#
ALTER TABLE cb.asb_dep_abast_agua_p
  DROP CONSTRAINT asb_dep_abast_agua_p_id_complexo_abast_agua_fk#
ALTER TABLE cb.asb_dep_saneamento
  DROP CONSTRAINT asb_dep_saneamento_id_complexo_saneamento_fk#
ALTER TABLE cb.asb_dep_saneamento_a
  DROP CONSTRAINT asb_dep_saneamento_a_id_complexo_saneamento_fk#
ALTER TABLE cb.asb_dep_saneamento_p
  DROP CONSTRAINT asb_dep_saneamento_p_id_complexo_saneamento_fk#
ALTER TABLE cb.asb_edif_abast_agua_a
  DROP CONSTRAINT asb_edif_abast_agua_a_id_complexo_abast_agua_fk#
ALTER TABLE cb.asb_edif_abast_agua_p
  DROP CONSTRAINT asb_edif_abast_agua_p_id_complexo_abast_agua_fk#
ALTER TABLE cb.asb_edif_saneamento_a
  DROP CONSTRAINT asb_edif_saneamento_a_id_complexo_saneamento_fk#
ALTER TABLE cb.asb_edif_saneamento_p
  DROP CONSTRAINT asb_edif_saneamento_p_id_complexo_saneamento_fk#
ALTER TABLE cb.eco_area_agrop_ext_veg_pesca_a
  DROP CONSTRAINT eco_area_agrop_ext_veg_pesca_a_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_area_comerc_serv_a
  DROP CONSTRAINT eco_area_comerc_serv_a_id_org_comerc_serv_fk#
ALTER TABLE cb.eco_area_ext_mineral_a
  DROP CONSTRAINT eco_area_ext_mineral_a_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_area_industrial_a
  DROP CONSTRAINT eco_area_industrial_a_id_org_industrial_fk#
ALTER TABLE cb.eco_deposito_geral
  DROP CONSTRAINT eco_deposito_geral_id_org_comerc_serv_fk#
ALTER TABLE cb.eco_deposito_geral
  DROP CONSTRAINT eco_deposito_geral_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_deposito_geral
  DROP CONSTRAINT eco_deposito_geral_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_deposito_geral
  DROP CONSTRAINT eco_deposito_geral_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.eco_deposito_geral
  DROP CONSTRAINT eco_deposito_geral_id_estrut_transporte_fk#
ALTER TABLE cb.eco_deposito_geral_a
  DROP CONSTRAINT eco_deposito_geral_a_id_org_comerc_serv_fk#
ALTER TABLE cb.eco_deposito_geral_a
  DROP CONSTRAINT eco_deposito_geral_a_id_estrut_transporte_fk#
ALTER TABLE cb.eco_deposito_geral_a
  DROP CONSTRAINT eco_deposito_geral_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.eco_deposito_geral_a
  DROP CONSTRAINT eco_deposito_geral_a_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_deposito_geral_a
  DROP CONSTRAINT eco_deposito_geral_a_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_deposito_geral_p
  DROP CONSTRAINT eco_deposito_geral_p_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_deposito_geral_p
  DROP CONSTRAINT eco_deposito_geral_p_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.eco_deposito_geral_p
  DROP CONSTRAINT eco_deposito_geral_p_id_estrut_transporte_fk#
ALTER TABLE cb.eco_deposito_geral_p
  DROP CONSTRAINT eco_deposito_geral_p_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_deposito_geral_p
  DROP CONSTRAINT eco_deposito_geral_p_id_org_comerc_serv_fk#
ALTER TABLE cb.eco_edif_agrop_ext_veg_pesca_a
  DROP CONSTRAINT eco_edif_agrop_ext_veg_pesca_a_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_edif_agrop_ext_veg_pesca_p
  DROP CONSTRAINT eco_edif_agrop_ext_veg_pesca_p_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_edif_comerc_serv_a
  DROP CONSTRAINT eco_edif_comerc_serv_a_id_org_comerc_serv_fk#
ALTER TABLE cb.eco_edif_comerc_serv_p
  DROP CONSTRAINT eco_edif_comerc_serv_p_id_org_comerc_serv_fk#
ALTER TABLE cb.eco_edif_ext_mineral_a
  DROP CONSTRAINT eco_edif_ext_mineral_a_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_edif_ext_mineral_p
  DROP CONSTRAINT eco_edif_ext_mineral_p_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_edif_industrial_a
  DROP CONSTRAINT eco_edif_industrial_a_id_org_industrial_fk#
ALTER TABLE cb.eco_edif_industrial_p
  DROP CONSTRAINT eco_edif_industrial_p_id_org_industrial_fk#
ALTER TABLE cb.eco_equip_agropec
  DROP CONSTRAINT eco_equip_agropec_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_equip_agropec_a
  DROP CONSTRAINT eco_equip_agropec_a_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_equip_agropec_l
  DROP CONSTRAINT eco_equip_agropec_l_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_equip_agropec_p
  DROP CONSTRAINT eco_equip_agropec_p_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE cb.eco_ext_mineral
  DROP CONSTRAINT eco_ext_mineral_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_ext_mineral_a
  DROP CONSTRAINT eco_ext_mineral_a_id_org_ext_mineral_fk#
ALTER TABLE cb.eco_ext_mineral_p
  DROP CONSTRAINT eco_ext_mineral_p_id_org_ext_mineral_fk#
ALTER TABLE complexos.eco_frigorifico_matadouro
  DROP CONSTRAINT eco_frigorifico_matadouro_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE complexos.eco_frigorifico_matadouro
  DROP CONSTRAINT eco_frigorifico_matadouro_id_org_pub_civil_fk#
ALTER TABLE complexos.eco_frigorifico_matadouro
  DROP CONSTRAINT eco_frigorifico_matadouro_id_org_pub_militar_fk#
ALTER TABLE complexos.eco_madeireira
  DROP CONSTRAINT eco_madeireira_id_org_pub_civil_fk#
ALTER TABLE complexos.eco_madeireira
  DROP CONSTRAINT eco_madeireira_id_org_agropec_ext_veg_pesca_fk#
ALTER TABLE complexos.eco_madeireira
  DROP CONSTRAINT eco_madeireira_id_org_pub_militar_fk#
ALTER TABLE complexos.eco_org_industrial
  DROP CONSTRAINT eco_org_industrial_id_org_pub_militar_fk#
ALTER TABLE complexos.eco_org_industrial
  DROP CONSTRAINT eco_org_industrial_id_org_pub_civil_fk#
ALTER TABLE cb.edu_area_ensino_a
  DROP CONSTRAINT edu_area_ensino_a_id_org_ensino_fk#
ALTER TABLE cb.edu_area_lazer_a
  DROP CONSTRAINT edu_area_lazer_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_area_religiosa_a
  DROP CONSTRAINT edu_area_religiosa_a_id_org_religiosa_fk#
ALTER TABLE cb.edu_area_ruinas_a
  DROP CONSTRAINT edu_area_ruinas_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_arquibancada
  DROP CONSTRAINT edu_arquibancada_id_complexo_lazer_fk#
ALTER TABLE cb.edu_arquibancada_a
  DROP CONSTRAINT edu_arquibancada_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_arquibancada_p
  DROP CONSTRAINT edu_arquibancada_p_id_complexo_lazer_fk#
ALTER TABLE cb.edu_campo_quadra
  DROP CONSTRAINT edu_campo_quadra_id_complexo_lazer_fk#
ALTER TABLE cb.edu_campo_quadra_a
  DROP CONSTRAINT edu_campo_quadra_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_campo_quadra_p
  DROP CONSTRAINT edu_campo_quadra_p_id_complexo_lazer_fk#
ALTER TABLE complexos.edu_complexo_lazer
  DROP CONSTRAINT edu_complexo_lazer_id_org_pub_civil_fk#
ALTER TABLE complexos.edu_complexo_lazer
  DROP CONSTRAINT edu_complexo_lazer_id_org_pub_militar_fk#
ALTER TABLE complexos.edu_complexo_lazer
  DROP CONSTRAINT edu_complexo_lazer_id_org_ensino_fk#
ALTER TABLE complexos.edu_complexo_lazer
  DROP CONSTRAINT edu_complexo_lazer_id_org_religiosa_fk#
ALTER TABLE cb.edu_coreto_tribuna
  DROP CONSTRAINT edu_coreto_tribuna_id_complexo_lazer_fk#
ALTER TABLE cb.edu_coreto_tribuna_a
  DROP CONSTRAINT edu_coreto_tribuna_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_coreto_tribuna_p
  DROP CONSTRAINT edu_coreto_tribuna_p_id_complexo_lazer_fk#
ALTER TABLE cb.edu_edif_const_lazer_a
  DROP CONSTRAINT edu_edif_const_lazer_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_edif_const_lazer_p
  DROP CONSTRAINT edu_edif_const_lazer_p_id_complexo_lazer_fk#
ALTER TABLE cb.edu_edif_const_turistica_a
  DROP CONSTRAINT edu_edif_const_turistica_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_edif_const_turistica_p
  DROP CONSTRAINT edu_edif_const_turistica_p_id_complexo_lazer_fk#
ALTER TABLE cb.edu_edif_ensino_a
  DROP CONSTRAINT edu_edif_ensino_a_id_org_ensino_fk#
ALTER TABLE cb.edu_edif_ensino_p
  DROP CONSTRAINT edu_edif_ensino_p_id_org_ensino_fk#
ALTER TABLE cb.edu_edif_religiosa_a
  DROP CONSTRAINT edu_edif_religiosa_a_id_org_religiosa_fk#
ALTER TABLE cb.edu_edif_religiosa_p
  DROP CONSTRAINT edu_edif_religiosa_p_id_org_religiosa_fk#
ALTER TABLE complexos.edu_org_ensino_militar
  DROP CONSTRAINT edu_org_ensino_militar_id_org_pub_militar_fk#
ALTER TABLE complexos.edu_org_ensino_pub
  DROP CONSTRAINT edu_org_ensino_pub_id_org_pub_civil_fk#
ALTER TABLE complexos.edu_org_ensino_religioso
  DROP CONSTRAINT edu_org_ensino_religioso_id_org_religiosa_fk#
ALTER TABLE cb.edu_piscina_a
  DROP CONSTRAINT edu_piscina_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_pista_competicao_l
  DROP CONSTRAINT edu_pista_competicao_l_id_complexo_lazer_fk#
ALTER TABLE cb.edu_ruina
  DROP CONSTRAINT edu_ruina_id_complexo_lazer_fk#
ALTER TABLE cb.edu_ruina_a
  DROP CONSTRAINT edu_ruina_a_id_complexo_lazer_fk#
ALTER TABLE cb.edu_ruina_p
  DROP CONSTRAINT edu_ruina_p_id_complexo_lazer_fk#
ALTER TABLE cb.enc_antena_comunic_p
  DROP CONSTRAINT enc_antena_comunic_p_id_complexo_comunicacao_fk#
ALTER TABLE cb.enc_area_comunicacao_a
  DROP CONSTRAINT enc_area_comunicacao_a_id_complexo_comunicacao_fk#
ALTER TABLE cb.enc_area_energia_eletrica_a
  DROP CONSTRAINT enc_area_energia_eletrica_a_id_subestacao_ener_eletr_fk#
ALTER TABLE cb.enc_area_energia_eletrica_a
  DROP CONSTRAINT enc_area_energia_eletrica_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE complexos.enc_complexo_comunicacao
  DROP CONSTRAINT enc_complexo_comunicacao_id_org_comerc_serv_fk#
ALTER TABLE complexos.enc_complexo_gerad_energ_eletr
  DROP CONSTRAINT enc_complexo_gerad_energ_eletr_id_org_comerc_serv_fk#
ALTER TABLE cb.enc_edif_comunic_a
  DROP CONSTRAINT enc_edif_comunic_a_id_complexo_comunicacao_fk#
ALTER TABLE cb.enc_edif_comunic_p
  DROP CONSTRAINT enc_edif_comunic_p_id_complexo_comunicacao_fk#
ALTER TABLE cb.enc_edif_energia_a
  DROP CONSTRAINT enc_edif_energia_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_edif_energia_a
  DROP CONSTRAINT enc_edif_energia_a_id_subestacao_ener_eletr_fk#
ALTER TABLE cb.enc_edif_energia_p
  DROP CONSTRAINT enc_edif_energia_p_id_subestacao_ener_eletr_fk#
ALTER TABLE cb.enc_edif_energia_p
  DROP CONSTRAINT enc_edif_energia_p_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_est_gerad_energia_eletr
  DROP CONSTRAINT enc_est_gerad_energia_eletr_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_est_gerad_energia_eletr_a
  DROP CONSTRAINT enc_est_gerad_energia_eletr_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_est_gerad_energia_eletr_l
  DROP CONSTRAINT enc_est_gerad_energia_eletr_l_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_est_gerad_energia_eletr_p
  DROP CONSTRAINT enc_est_gerad_energia_eletr_p_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_grupo_transformadores
  DROP CONSTRAINT enc_grupo_transformadores_id_subestacao_ener_eletr_fk#
ALTER TABLE cb.enc_grupo_transformadores_a
  DROP CONSTRAINT enc_grupo_transformadores_a_id_subestacao_ener_eletr_fk#
ALTER TABLE cb.enc_grupo_transformadores_p
  DROP CONSTRAINT enc_grupo_transformadores_p_id_subestacao_ener_eletr_fk#
ALTER TABLE cb.enc_hidreletrica_a
  DROP CONSTRAINT enc_hidreletrica_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_hidreletrica_l
  DROP CONSTRAINT enc_hidreletrica_l_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_hidreletrica_p
  DROP CONSTRAINT enc_hidreletrica_p_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE complexos.enc_subestacao_ener_eletr
  DROP CONSTRAINT enc_subestacao_ener_eletr_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_termeletrica_a
  DROP CONSTRAINT enc_termeletrica_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_termeletrica_p
  DROP CONSTRAINT enc_termeletrica_p_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.enc_torre_comunic_p
  DROP CONSTRAINT enc_torre_comunic_p_id_complexo_comunicacao_fk#
ALTER TABLE cb.enc_trecho_comunic_l
  DROP CONSTRAINT enc_trecho_comunic_l_id_org_comerc_serv_fk#
ALTER TABLE cb.enc_trecho_energia_l
  DROP CONSTRAINT enc_trecho_energia_l_id_org_comerc_serv_fk#
ALTER TABLE cb.hid_barragem
  DROP CONSTRAINT hid_barragem_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.hid_barragem_a
  DROP CONSTRAINT hid_barragem_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.hid_barragem_l
  DROP CONSTRAINT hid_barragem_l_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.hid_barragem_p
  DROP CONSTRAINT hid_barragem_p_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.hid_reservatorio_hidrico_a
  DROP CONSTRAINT hid_reservatorio_hidrico_a_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE complexos.hid_trecho_curso_dagua
  DROP CONSTRAINT hid_trecho_curso_dagua_id_curso_dagua_fk#
ALTER TABLE cb.hid_trecho_drenagem_l
  DROP CONSTRAINT hid_trecho_drenagem_l_id_trecho_curso_dagua_fk#
ALTER TABLE cb.hid_trecho_massa_dagua_a
  DROP CONSTRAINT hid_trecho_massa_dagua_a_id_trecho_curso_dagua_fk#
ALTER TABLE cb.loc_area_habitacional_a
  DROP CONSTRAINT loc_area_habitacional_a_id_complexo_habitacional_fk#
ALTER TABLE cb.loc_edif_habitacional_a
  DROP CONSTRAINT loc_edif_habitacional_a_id_complexo_habitacional_fk#
ALTER TABLE cb.loc_edif_habitacional_p
  DROP CONSTRAINT loc_edif_habitacional_p_id_complexo_habitacional_fk#
ALTER TABLE cb.loc_hab_indigena
  DROP CONSTRAINT loc_hab_indigena_id_aldeia_indigena_fk#
ALTER TABLE cb.loc_hab_indigena_a
  DROP CONSTRAINT loc_hab_indigena_a_id_aldeia_indigena_fk#
ALTER TABLE cb.loc_hab_indigena_p
  DROP CONSTRAINT loc_hab_indigena_p_id_aldeia_indigena_fk#
ALTER TABLE cb.pto_area_est_med_fenom_a
  DROP CONSTRAINT pto_area_est_med_fenom_a_id_est_med_fenomenos_fk#
ALTER TABLE complexos.pto_est_med_fenomenos
  DROP CONSTRAINT pto_est_med_fenomenos_id_est_med_fenomenos_fk#
ALTER TABLE cb.pto_pto_est_med_fenomenos_p
  DROP CONSTRAINT pto_pto_est_med_fenomenos_p_id_est_med_fenomenos_fk#
ALTER TABLE cb.sau_area_saude_a
  DROP CONSTRAINT sau_area_saude_a_id_org_saude_fk#
ALTER TABLE cb.sau_area_servico_social_a
  DROP CONSTRAINT sau_area_servico_social_a_id_org_servico_social_fk#
ALTER TABLE cb.sau_edif_saude_a
  DROP CONSTRAINT sau_edif_saude_a_id_org_saude_fk#
ALTER TABLE cb.sau_edif_saude_p
  DROP CONSTRAINT sau_edif_saude_p_id_org_saude_fk#
ALTER TABLE cb.sau_edif_servico_social_a
  DROP CONSTRAINT sau_edif_servico_social_a_id_org_servico_social_fk#
ALTER TABLE cb.sau_edif_servico_social_p
  DROP CONSTRAINT sau_edif_servico_social_p_id_org_servico_social_fk#
ALTER TABLE complexos.sau_org_saude_militar
  DROP CONSTRAINT sau_org_saude_militar_id_org_pub_militar_fk#
ALTER TABLE complexos.sau_org_saude_pub
  DROP CONSTRAINT sau_org_saude_pub_id_org_pub_civil_fk#
ALTER TABLE complexos.sau_org_servico_social_pub
  DROP CONSTRAINT sau_org_servico_social_pub_id_org_pub_civil_fk#
ALTER TABLE cb.tra_area_estrut_transporte_a
  DROP CONSTRAINT tra_area_estrut_transporte_a_id_estrut_transporte_fk#
ALTER TABLE cb.tra_atracadouro
  DROP CONSTRAINT tra_atracadouro_id_complexo_portuario_fk#
ALTER TABLE cb.tra_atracadouro_a
  DROP CONSTRAINT tra_atracadouro_a_id_complexo_portuario_fk#
ALTER TABLE cb.tra_atracadouro_l
  DROP CONSTRAINT tra_atracadouro_l_id_complexo_portuario_fk#
ALTER TABLE cb.tra_atracadouro_p
  DROP CONSTRAINT tra_atracadouro_p_id_complexo_portuario_fk#
ALTER TABLE cb.tra_caminho_aereo_l
  DROP CONSTRAINT tra_caminho_aereo_l_id_org_ext_mineral_fk#
ALTER TABLE cb.tra_condutor_hidrico_l
  DROP CONSTRAINT tra_condutor_hidrico_l_id_complexo_gerad_energ_eletr_fk#
ALTER TABLE cb.tra_condutor_hidrico_l
  DROP CONSTRAINT tra_condutor_hidrico_l_id_duto_fk#
ALTER TABLE cb.tra_edif_constr_aeroportuaria_a
  DROP CONSTRAINT tra_edif_constr_aeroportuaria_a_id_complexo_aeroportuario_fk#
ALTER TABLE cb.tra_edif_constr_aeroportuaria_p
  DROP CONSTRAINT tra_edif_constr_aeroportuaria_p_id_complexo_aeroportuario_fk#
ALTER TABLE cb.tra_edif_constr_portuaria_a
  DROP CONSTRAINT tra_edif_constr_portuaria_a_id_complexo_portuario_fk#
ALTER TABLE cb.tra_edif_constr_portuaria_p
  DROP CONSTRAINT tra_edif_constr_portuaria_p_id_complexo_portuario_fk#
ALTER TABLE cb.tra_edif_metro_ferroviaria_a
  DROP CONSTRAINT tra_edif_metro_ferroviaria_a_id_estrut_apoio_fk#
ALTER TABLE cb.tra_edif_metro_ferroviaria_p
  DROP CONSTRAINT tra_edif_metro_ferroviaria_p_id_estrut_apoio_fk#
ALTER TABLE cb.tra_edif_rodoviaria_a
  DROP CONSTRAINT tra_edif_rodoviaria_a_id_estrut_apoio_fk#
ALTER TABLE cb.tra_edif_rodoviaria_p
  DROP CONSTRAINT tra_edif_rodoviaria_p_id_estrut_apoio_fk#
ALTER TABLE cb.tra_fundeadouro
  DROP CONSTRAINT tra_fundeadouro_id_complexo_portuario_fk#
ALTER TABLE cb.tra_fundeadouro_a
  DROP CONSTRAINT tra_fundeadouro_a_id_complexo_portuario_fk#
ALTER TABLE cb.tra_fundeadouro_l
  DROP CONSTRAINT tra_fundeadouro_l_id_complexo_portuario_fk#
ALTER TABLE cb.tra_fundeadouro_p
  DROP CONSTRAINT tra_fundeadouro_p_id_complexo_portuario_fk#
ALTER TABLE cb.tra_funicular
  DROP CONSTRAINT tra_funicular_id_org_ext_mineral_fk#
ALTER TABLE cb.tra_funicular_l
  DROP CONSTRAINT tra_funicular_l_id_org_ext_mineral_fk#
ALTER TABLE cb.tra_funicular_p
  DROP CONSTRAINT tra_funicular_p_id_org_ext_mineral_fk#
ALTER TABLE cb.tra_girador_ferroviario_p
  DROP CONSTRAINT tra_girador_ferroviario_p_id_estrut_apoio_fk#
ALTER TABLE cb.tra_identific_trecho_rod_p
  DROP CONSTRAINT tra_identific_trecho_rod_p_id_via_rodoviaria_fk#
ALTER TABLE cb.tra_patio
  DROP CONSTRAINT tra_patio_id_org_industrial_fk#
ALTER TABLE cb.tra_patio
  DROP CONSTRAINT tra_patio_id_org_ensino_fk#
ALTER TABLE cb.tra_patio
  DROP CONSTRAINT tra_patio_id_org_comerc_serv_fk#
ALTER TABLE cb.tra_patio
  DROP CONSTRAINT tra_patio_id_org_ext_mineral_fk#
ALTER TABLE cb.tra_patio
  DROP CONSTRAINT tra_patio_id_estrut_transporte_fk#
ALTER TABLE cb.tra_patio_a
  DROP CONSTRAINT tra_patio_a_id_org_industrial_fk#
ALTER TABLE cb.tra_patio_a
  DROP CONSTRAINT tra_patio_a_id_estrut_transporte_fk#
ALTER TABLE cb.tra_patio_a
  DROP CONSTRAINT tra_patio_a_id_org_ext_mineral_fk#
ALTER TABLE cb.tra_patio_a
  DROP CONSTRAINT tra_patio_a_id_org_comerc_serv_fk#
ALTER TABLE cb.tra_patio_a
  DROP CONSTRAINT tra_patio_a_id_org_ensino_fk#
ALTER TABLE cb.tra_patio_p
  DROP CONSTRAINT tra_patio_p_id_org_ensino_fk#
ALTER TABLE cb.tra_patio_p
  DROP CONSTRAINT tra_patio_p_id_org_ext_mineral_fk#
ALTER TABLE cb.tra_patio_p
  DROP CONSTRAINT tra_patio_p_id_org_comerc_serv_fk#
ALTER TABLE cb.tra_patio_p
  DROP CONSTRAINT tra_patio_p_id_org_industrial_fk#
ALTER TABLE cb.tra_patio_p
  DROP CONSTRAINT tra_patio_p_id_estrut_transporte_fk#
ALTER TABLE cb.tra_pista_ponto_pouso
  DROP CONSTRAINT tra_pista_ponto_pouso_id_complexo_aeroportuario_fk#
ALTER TABLE cb.tra_pista_ponto_pouso_a
  DROP CONSTRAINT tra_pista_ponto_pouso_a_id_complexo_aeroportuario_fk#
ALTER TABLE cb.tra_pista_ponto_pouso_l
  DROP CONSTRAINT tra_pista_ponto_pouso_l_id_complexo_aeroportuario_fk#
ALTER TABLE cb.tra_pista_ponto_pouso_p
  DROP CONSTRAINT tra_pista_ponto_pouso_p_id_complexo_aeroportuario_fk#
ALTER TABLE cb.tra_trecho_duto_l
  DROP CONSTRAINT tra_trecho_duto_l_id_duto_fk#
ALTER TABLE cb.tra_trecho_ferroviario_l
  DROP CONSTRAINT tra_trecho_ferroviario_l_id_via_ferrea_fk#
ALTER TABLE cb.tra_trecho_hidroviario_l
  DROP CONSTRAINT tra_trecho_hidroviario_l_id_hidrovia_fk#
ALTER TABLE cb.tra_trecho_rodoviario_l
  DROP CONSTRAINT tra_trecho_rodoviario_l_id_via_rodoviaria_fk#
